services:
  redis:
    image: redis:7
    restart: unless-stopped

  safepaw:
    build: .
    command: pixi run -m backend python -m uvicorn backend.run:app --host 0.0.0.0 --port 5000
    expose:
      - "5000"
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      DATABASE_URL: sqlite:////app/data/database.sqlite
      REDIS_HOST: redis
    networks:
      - default
      - web
    volumes:
    - ./data:/app/data
    - ./experiments:/app/experiments

  worker:
    build: .
    command: rq worker -u redis://redis:6379 safepaw
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
    volumes:
    - ./data:/app/data
    - ./experiments:/app/experiments

networks:
  web:
    external: true
    name: debian_web
