project:
  type: website

bibliography: references.bib

website:
  title: "SAFEPAW Documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: instance_maternities.qmd
        text: Maternity Wards
      - href: instance_pthptg.qmd
        text : Hip and Knee Arthoplasty
      - about.qmd
      
    

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
  pdf:
    geometry:
      - landscape
    include-in-header:
      text: |
        \usepackage{adjustbox}
        \usepackage{longtable}
        \usepackage{booktabs}